name: CI

on:
  schedule:
    - cron:  '30 1 * * *'  
  push:

jobs:
  build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        nmake init_vcpkg
        nmake openssl 
        nmake libevent
        nmake libconfig
        nmake asio
        nmake pthreads
        try {nmake libparc} catch System.Exception {}
        try {nmake hicn } catch System.Exception {}
