name: CI

on:
  schedule:
    - cron:  '30 1 * * *'  
  push:

jobs:
  build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        @echo off
        rem Args[x]: nmake arguments
        echo.>> %~n0.log
        echo %date% %time%>> %~n0.log
        echo nmake /NOLOGO %*>> %~n0.log
        nmake init_vcpkg
        nmake openssl 
        nmake libevent
        nmake libconfig
        nmake asio
        nmake pthreads
        nmake libparc
        nmake hicn
        echo %errorlevel%>> %~n0.log
